In [13]:
import numpy as np

In [14]:
# Q1 — Array Information
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)
print("Total Bytes:", arr.nbytes)

[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8
Total Bytes: 48


In [15]:
# Q2 — Choosing the Correct Function
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [16]:
# Q3 — Understanding linspace
arr = np.linspace(0,100,11)
arr

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
# Q4— Build Without Copying
arr = np.full((3,4),5)
print(arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Total Bytes:", arr.nbytes)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Total Bytes: 96


In [57]:
# Q5— Reshape & Indexing
arr = np.arange(1,13).reshape(3,4)
print(arr[2,:])
print(arr[:,2])
print(arr[2,3])
print(arr[:2,:3])

[ 9 10 11 12]
[ 3  7 11]
12
[[1 2 3]
 [5 6 7]]


In [132]:
# Real-World Problems
# Problem 1 — Dataset Preprocessing
data = np.array([[70,80,90],[60,75,85],[90,95,88],[45,55,60],[80,85,92]])
average = np.sum(data,axis=1)/3
average>80
maths_marks = data[:,0]
highest_marks_maths = np.max(maths_marks)
print("Highest Marks in Maths:",highest_marks_maths)
physics_marks = data[:,1]
highest_marks_physics = np.max(physics_marks)
print("Highest Marks in Physics:",highest_marks_physics)
python_marks = data[:,2]
highest_marks_python = np.max(python_marks)
print("Highest Marks in Python:",highest_marks_python)
np.argmax(python_marks)
bonus = [5,3,2]
final_marks = data+bonus
final_average = np.sum(final_marks ,axis=1)/3
final_average

Highest Marks in Maths: 90
Highest Marks in Physics: 95
Highest Marks in Python: 92


array([83.33333333, 76.66666667, 94.33333333, 56.66666667, 89.        ])

In [ ]:
# Real-World Problems
# Problem 1 — Dataset Preprocessing
data = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [90, 95, 88],
    [45, 55, 60],
    [80, 85, 92]
])
student_averages = np.mean(data, axis=1)
print("Averages:", student_averages)
mask = student_averages > 80
top_students_data = data[mask]
print("Top students data:\n", top_students_data)
highest_per_subject = np.max(data, axis=0)
print("Highest in each subject (Math, Physics, Python):", highest_per_subject)
python_scores = data[:, 2]
highest_python_index = np.argmax(python_scores)
print("Index of highest Python score:", highest_python_index)
bonus_marks = np.array([5, 3, 2])
new_data = data + bonus_marks
new_averages = np.mean(new_data, axis=1)
print("New Data:\n", new_data)
print("New Averages:", new_averages)

Averages: [80.         73.33333333 91.         53.33333333 85.66666667]
Top students data:
 [[90 95 88]
 [80 85 92]]
Highest in each subject (Math, Physics, Python): [90 95 92]
Index of highest Python score: 4
New Data:
 [[75 83 92]
 [65 78 87]
 [95 98 90]
 [50 58 62]
 [85 88 94]]
New Averages: [83.33333333 76.66666667 94.33333333 56.66666667 89.        ]


In [158]:
# Problem 2 — Image-Like Data
image = np.array([
    [
        [100, 120, 140],
        [110, 130, 150],
        [120, 140, 160]
    ],
    [
        [200, 180, 160],
        [210, 190, 170],
        [220, 200, 180]
    ]
])
print(image.shape)
print(image.ndim)
print(image.size)
red_channel = image[:,:,0]
print(red_channel)
green_channel = image[:,:,1]
print(green_channel)
blue_channel = image[:,:,2]
print(blue_channel)
brightness = 20
print(image+brightness)
brightness2 = [10,20,30]
print(image+brightness2)
cropped_image = image[0,1:3,:]
print(cropped_image)
mask = image>180
print(image[mask])

(2, 3, 3)
3
18
[[100 110 120]
 [200 210 220]]
[[120 130 140]
 [180 190 200]]
[[140 150 160]
 [160 170 180]]
[[[120 140 160]
  [130 150 170]
  [140 160 180]]

 [[220 200 180]
  [230 210 190]
  [240 220 200]]]
[[[110 140 170]
  [120 150 180]
  [130 160 190]]

 [[210 200 190]
  [220 210 200]
  [230 220 210]]]
[[110 130 150]
 [120 140 160]]
[200 210 190 220 200]
